/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class Library {
    AnotherClass another = new AnotherClass()

    boolean someLibraryMethod(boolean isChained = false) {
        if(!isChained && another.currentValue) {
            throw new Exception("Nope")
        }

        throw new Exception("BOOM")
    }
}

class AnotherClass {
    String name = 'Foo'

    boolean isCurrentValue() {
        return false
    }
}